### ISSUE TITLE
possible fix for `unable_to_load_module x in path y`

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#123]
I get this type of error every time I restart my R-session and first try to load a custom module. After the first error, it tends to go away.

```
Error in box::use(./module_name) : 
  unable to load module “./module_name”; not found in “/directory/path”
```

@caldwellst @hannahker  - do you get this also? I guess the GH runner doesnt!?

@caldwellst I remember we talked about this somewhere , but don't think we came to a clear solution and I wasn't able easily find the discussion.

Anways, the  [{box} FAQ page](https://klmr.me/box/articles/faq.html) describes a very similar, but slightly different (I think) error message and the solution proposed it just to run this:

```
box::use(r/core[...])
```

This does stop the error from occurring on my computer as well. It seems kind of annoying to put at the top of every script though. If this is in fact a good solution, I wonder if it could possibly make sense/work to have some sort of onLoad() type deal for it .

**Comment by caldwellst** [comment]
That's not what using the core functions does. `box::use(r/core[...])` solves the error you find if you try to run functions like `View()` or `read.csv()`, because they are not attached by default in `{box}`. So, you have to do:

```r
box::use(utils)
utils$View()
utils$read.csv()`
```

The error you describe above is one that I get when I am interactively running line by line through a script in RStudio into my R console. It seems to be an error with not recognising the relevant pathing, but has nothing to do with the solution above, hence why there are never errors if you run the scripts from your terminal or on GitHub Actions. I've tried to look for this issue on the `{box}` repo before, but haven't found anything. Will have a look again and post something on there.

**Comment by caldwellst** [comment]
https://github.com/klmr/box/issues/365

**Comment by zackarno** [comment]
yea interesting, but  I wonder why `box::use(r/core[...])` does fix it!? I wonder if one of those non-base, but core packages that are typically loaded in R-sessions somehow help?

glad you opened an issue though - that should help!

Two additional things I noticed:

- Don't think it has to do w/ `command` + `enter` workflow. Happens if you just copy paste into the console.
- Does not happen if you are working in script saved to root `.rproj` directory.

**Comment by caldwellst** [comment]
Closing, and we can hopefully get some information in https://github.com/klmr/box/issues/365. However, may be an issue outside of the control of `{box}`, remains to be seen what the maintainer of `{box}` thinks.
