### ISSUE TITLE
add offset to food insecurity P labels (or legend)

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#189]
Can't read the P3 label in the latest email from today. We could either create an offset for the label from most recent date point or just have a 3 category legend?

<img width="211" alt="image" src="https://github.com/OCHA-DAP/hdx-signals/assets/23731112/086e256a-8909-4f91-8adc-726ad6834de2">

**Comment by caldwellst** [comment]
Good catch! We are already using `ggrepel::geom_text_repel()`, it seems it hasn't worked in this instance. I didn't do an offset because often, the P5 data was 0%, so sat on the x-axis, so `geom_text_repel()` has the advantage of also lifting the label above the line, as well as away from the points. However, failed here! Maybe we could adjust the weight of the `geom_point()` values so that this doesn't happen again? I forget how the force is set in `{ggrepel}`, but I imagine there's a way to weight various geoms.

**Comment by caldwellst** [comment]
Addressed in #199. May continue to be finicky, but hard to tell until we come across new cases.
