### ISSUE TITLE
use `file.path()` instead of "/" for parquet in blob?

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#47]
suggest  using the typical `file.path()` instead of `/` to write paths for azure blob files. It might not matter in this specific context, but then again better safe than sorry.

probably can just do a search for ".parquet" in repo and replace paths like that

**Comment by caldwellst** [comment]
This is the opposite behaviour you want, because `file.path()` is designed to provide system specific file separators using `fsep`. Except, we ALWAYS want `/` because we are only reading to and from the Azure store, which is system independent, not system specific. Could use `file.path(..., fsep = "/")`, but might as well just use `paste()` at that point.

**Comment by zackarno** [comment]
ok got it!
