### ISSUE TITLE
question on how to manually walk through funcs -- `generate_signals(..., overwrite_content = TRUE)`

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#49]
Was walking through `update_replacement.R` -- when i get here 

```
# now generate signals individually for each displacement type
df_conflict <- generate_signals(
  df_wrangled = dplyr$filter(df_wrangled, displacement_type == "Conflict"),
  df_raw = dplyr$filter(df_raw, displacement_type == "Conflict"),
  indicator_id = "idmc_displacement_conflict",
  alert_fn = alert_displacement$alert,
  plot_fn = plot_displacement$plot,
  info_fn = info_displacement$info,
  summary_fn = summary_displacement$summary,
  first_run = TRUE
)
```

the message below (originating from`check_existing_signals()`) pops up -- it's informative, but i just want to walk through functions and am hesitant to do anything that would overwrite content -- what do you recommend

```
Error: The idmc_displacement_conflict signals data
output/idmc_displacement_conflict/signals.parquet on Azure is non-empty. Please
triage this data into `output/signals.parquet` prior to generating new signals
by running `triage_signals()`. If you want to re-create content on this existing
dataset, then you should run `generate_signals(..., overwrite_content = TRUE)`
```

**Comment by caldwellst** [comment]
You can't overwrite content if `Sys.getenv(GMAS_TEST_RUN)` is `TRUE`, the default if it's set or unset. You would have to manually set that to `FALSE` to overwrite content. I think the best option would be to just manually bypass this error and continue on in the code. I think I will avoid creating functions or capacity to do this , because it would only be in the rarest of circumstances we want to bypass these checks, so making it difficult/requiring manual work I think is the best way to avoid manual overwriting.

Happy to help you walk through it as necessary!

**Comment by zackarno** [comment]
alright that sounds good... i think its fine to just skip that check in the debugging sequence
