### ISSUE TITLE
`filter_alerts_ongoing()` - question

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/hdx-signals#50]
`filter_alerts_ongoing()`
What is up with this `"1500-01-01"`?

https://github.com/OCHA-DAP/hdx-signals/blob/b4de37752e9cb1e2f0d53c544e41d4c33a5c4676/src/alerts/filter_alerts.R#L84-L86

another small question adding here:

`recursive_filter_country()`
comments says 90d, but then code looks like 180d
https://github.com/OCHA-DAP/hdx-signals/blob/b4de37752e9cb1e2f0d53c544e41d4c33a5c4676/src/alerts/filter_alerts.R#L140

**Comment by caldwellst** [comment]
The first one is removing warning if the `date` column is empty, because it will then return an `Inf` value with the warning. So by putting so generic date (that is so early in time it will never be the max of the vector, we can remove those errors. The errors only occur when the data frame is empt, so just putting this here controls for that.

On the latter, the comment was because I was previously separating out recent alerts within 90 days. But I'm no longer, so have adjusted, good catch!
