### ISSUE TITLE
Create system overview diagram

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/hdx-signals#59]
For project onboarding, it would be super helpful to have a basic diagram that gives an overview of this whole system. Ideally this could help answer questions like: 
- What external systems/APIs are we connecting to?
- What processes run regularly? How are these processes orchestrated/parameterized?
- What are the overall inputs and outputs?
- What are the intermediate artifacts created throughout the process? Where are these stored?
- Are there any static resources that the system requires? Where are these stored?

**Comment by hannahker** [comment]
Got a start here: https://drive.google.com/file/d/1tlAB7TWXGIUOtleyjgkRYJ853a8AeSAg/view?usp=sharing

Big WIP

<img width="906" alt="Screenshot 2024-05-08 at 3 14 29 PM" src="https://github.com/OCHA-DAP/hdx-signals/assets/25990216/c3156cd3-32d7-4142-a3d6-b90067bd5b3a">

**Comment by caldwellst** [comment]
Looks good! I don't think is too complex, so it's all pretty clear above. For public documentation, I think maybe we could reduce to an abstract flow for any indicator, so that we don't have to update every time new indicators arrive, and then within each indicators documentation, show where the data is sourced from and how we go from raw to wrangled.

**Comment by hannahker** [comment]
Yes, agreed! Some other pieces I'm trying to integrate:
- Static datasets and when/how those get updated
- The Mailchimp API and how that works
- How the triaging process works
