### ISSUE TITLE
Document local development setup and use of `HS_TEST` and `DRY_RUN` vars

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/hdx-signals#60]
It would be super useful to have documentation on the system functions in development vs in production. I know we have the `GMAS_TEST_RUN` flag, but is there anything else that we should be aware of when working locally, say? 

Some other questions that could hopefully be addressed:
- What needs to be done to test the full system end to end?
- Do we have any split in dev vs prod datasets?
- Anything else developers should be aware of when working locally?

**Comment by hannahker** [comment]
Somewhat related to #49

**Comment by caldwellst** [comment]
Yes, full documentation of this is critical! Will be working on in a week or two when documentation starts in full and we have the alerts running in test. As to your questions:

> What needs to be done to test the full system end to end?

The process for all indicators is contained in their `utils` folder, which contains functions for processing the data and plotting, mapping, and generating any other information for the campaign. All of these are used in the `update_...R` scripts at the top level of the indicator folder, and are then passed in to `generate_signals()`, which completely runs the entire process from generating signals, figuring out which we want to send emails for, creating the campaign content, and then creating the draft campaign. So essentially the end to end process can be seen entirely through that function.

However, we need an actual end to end test functionality to make sure everything works as necessary, and unit tests for all our functions. Something we can develop together, so once you're familiar with the system, we can build it based on your designs. I don't have much experience with testing beyond simple unit tests for functions, so hoping you can help with the overarching design and approach we take before we build it!

> Do we have any split in dev vs prod datasets?

Currently no. The only reason I am using `dev` is because Isa is creating pipelines to HDX from our Azure blob storage, which will keep the HDX Signals data up to date. However, she is unable to pipeline from `prod` currently, so I save a single CSV file out to dev for her to test with. Eventually will just use prod.

I do not think we need a dev/prod split, as we set up the structure within the blob to basically be about different quality of data, and think that is easier to use than dev/prod since everything is navigable in one location. But after your review of the system, again, let me know if you disagree!

> Anything else developers should be aware of when working locally?

Hmm, can't think of any off the top of my head, but we can edit the documentation to make sure the developer guidelines are clear and easy to follow.

**Comment by hannahker** [comment]
Closed with #211
